import { test, expect } from '@playwright/test'

import { mockBillPending } from './mocks/data'
import { loginAs } from './utils/api-mock'

test.describe('Automated Monthly Bill Generation (Display)', () => {
  test('Student sees new monthly bill generated by system', async ({ page }) => {
    // Note: We cannot test the cron job trigger (backend) in this frontend repo.
    // We verify that IF the system generates a bill, it is displayed correctly.

    await loginAs(page, 'student')

    const newBill = {
      ...mockBillPending,
      id: 'bill-new-month',
      month: '2',
      name: 'Kas Februari 2024',
    }

    // Mock bills list with the new bill
    await page.route(/\/api\/cash-bills\/my/, async (route) => {
      await route.fulfill({
        json: {
          success: true,
          data: { bills: [newBill], pagination: { totalItems: 1 } },
        },
      })
    })

    await page.goto('/user/tagihan-kas')
    // Wait for the bill to load (by checking a stable element)
    await page.waitForResponse(resp => resp.url().includes('/api/cash-bills/my') && resp.status() === 200);

    // Verify the new bill is visible using a specific locator for both Desktop (cell) and Mobile (heading)
    const billLocator = page
      .getByRole('cell', { name: 'Februari 2024' })
      .or(page.getByRole('heading', { name: 'Februari 2024' }));

    await expect(billLocator).toBeVisible({ timeout: 10000 })
  })
})
