import { test, expect } from '@playwright/test'

import { mockBillPending } from './mocks/data'
import { loginAs } from './utils/api-mock'

test.describe('Automated Monthly Bill Generation (Display)', () => {
  test('Student sees new monthly bill generated by system', async ({ page }) => {
    // Note: We verify that IF the system generates a bill, it is displayed correctly.

    await loginAs(page, 'student')

    const newBill = {
      ...mockBillPending,
      id: 'bill-new-month',
      month: '2',
      name: 'Kas Februari 2024',
    }

    // Mock bills list with the new bill
    await page.route(/\/api\/cash-bills\/my/, async (route) => {
      await route.fulfill({
        json: {
          success: true,
          data: { bills: [newBill], pagination: { totalItems: 1 } },
        },
      })
    })

    await page.goto('/user/tagihan-kas')
    // Wait for the bill to load (by checking a stable element)
    await page.waitForResponse(resp => resp.url().includes('/api/cash-bills/my') && resp.status() === 200);

    // Verify the new bill is visible
    // The UI displays the Month name (e.g. "Februari 2024") derived from the month number, not the bill name.

    await expect(page.getByText('Februari 2024').first()).toBeVisible({ timeout: 10000 })
  })
})
