/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login with NIM and password */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            /** @example 1313612345 */
            nim: string
            /** @example password123 */
            password: string
          }
        }
      }
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['LoginResponse']
          }
        }
        401: components['responses']['Unauthorized']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh access token */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            refreshToken: string
          }
        }
      }
      responses: {
        /** @description Token refreshed */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              success?: boolean
              data?: {
                accessToken?: string
                expiresIn?: number
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout and invalidate tokens */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Logged out successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get current user info */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description User info */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user profile */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description User profile */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserResponse']
          }
        }
      }
    }
    /** Update user profile */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            name?: string
            /** Format: email */
            email?: string
          }
        }
      }
      responses: {
        /** @description Profile updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Change password */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            oldPassword: string
            newPassword: string
            confirmPassword: string
          }
        }
      }
      responses: {
        /** @description Password changed */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/avatar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload avatar */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            avatar?: string
          }
        }
      }
      responses: {
        /** @description Avatar uploaded */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/dashboard/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get financial summary */
    get: {
      parameters: {
        query?: {
          startDate?: string
          endDate?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Financial summary */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DashboardSummary']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/dashboard/pending-bills': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get pending bills summary */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Pending bills */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/dashboard/pending-applications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get pending fund applications */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Pending applications */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transactions list */
    get: {
      parameters: {
        query?: {
          page?: components['parameters']['page']
          limit?: components['parameters']['limit']
          startDate?: string
          endDate?: string
          type?: 'income' | 'expense'
          sortBy?: 'date' | 'amount' | 'type'
          sortOrder?: 'asc' | 'desc'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of transactions */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TransactionListResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transactions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transaction details */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Transaction details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transactions/chart-data': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get chart data */
    get: {
      parameters: {
        query: {
          type: 'income' | 'expense'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Chart data */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transactions/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Export transactions */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['ExportRequest']
        }
      }
      responses: {
        /** @description Export URL */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/fund-applications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all fund applications */
    get: {
      parameters: {
        query?: {
          page?: components['parameters']['page']
          limit?: components['parameters']['limit']
          status?: 'pending' | 'approved' | 'rejected'
          category?: 'education' | 'health' | 'emergency' | 'equipment'
          minAmount?: number
          maxAmount?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of fund applications */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['FundApplicationListResponse']
          }
        }
      }
    }
    put?: never
    /** Create fund application */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'multipart/form-data': {
            purpose: string
            description?: string
            /** @enum {string} */
            category: 'education' | 'health' | 'emergency' | 'equipment'
            amount: number
            /** Format: binary */
            attachment?: string
          }
        }
      }
      responses: {
        /** @description Application created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/fund-applications/my': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get my fund applications */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description My applications */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/fund-applications/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get fund application details */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Application details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['FundApplicationDetail']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/cash-bills': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get my cash bills */
    get: {
      parameters: {
        query?: {
          page?: components['parameters']['page']
          limit?: components['parameters']['limit']
          status?: 'belum_dibayar' | 'menunggu_konfirmasi' | 'sudah_dibayar'
          month?: string
          year?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of cash bills */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CashBillListResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/cash-bills/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get cash bill details */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Bill details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CashBillDetail']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/cash-bills/{id}/pay': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit payment proof */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** @enum {string} */
            paymentMethod: 'bank' | 'ewallet' | 'cash'
            /** Format: binary */
            paymentProof: string
          }
        }
      }
      responses: {
        /** @description Payment submitted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/cash-bills/{id}/cancel-payment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel payment */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Payment cancelled */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/dashboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get treasurer dashboard */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Treasurer dashboard */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/fund-applications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all fund applications for review */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Applications for review */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/fund-applications/{id}/approve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Approve fund application
     * @description Approves the application and automatically creates an expense transaction
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Application approved */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/fund-applications/{id}/reject': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reject fund application */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            rejectionReason: string
          }
        }
      }
      responses: {
        /** @description Application rejected */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/cash-bills': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all cash bills */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description All cash bills */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/cash-bills/{id}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm payment
     * @description Confirms the payment and automatically creates an income transaction
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Payment confirmed */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/cash-bills/{id}/reject': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reject payment proof */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Payment rejected */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/rekap-kas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get financial recap */
    get: {
      parameters: {
        query?: {
          startDate?: string
          endDate?: string
          groupBy?: 'day' | 'week' | 'month' | 'year'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Financial recap */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/rekap-kas/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Export financial recap */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['ExportRequest']
        }
      }
      responses: {
        /** @description Export URL */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bendahara/students': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get class students */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of students */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ErrorResponse: {
      /** @example false */
      success?: boolean
      error?: {
        code?: string
        message?: string
        details?: Record<string, never>
      }
    }
    Pagination: {
      page?: number
      limit?: number
      totalItems?: number
      totalPages?: number
    }
    User: {
      /** Format: uuid */
      id?: string
      nim?: string
      name?: string
      email?: string
      /** @enum {string} */
      role?: 'user' | 'bendahara'
      /** Format: uuid */
      classId?: string
      className?: string
      avatarUrl?: string
    }
    UserResponse: {
      success?: boolean
      data?: components['schemas']['User']
    }
    LoginResponse: {
      success?: boolean
      data?: {
        user?: components['schemas']['User']
        tokens?: {
          accessToken?: string
          refreshToken?: string
          expiresIn?: number
        }
      }
    }
    DashboardSummary: {
      success?: boolean
      data?: {
        totalBalance?: number
        totalIncome?: number
        totalExpense?: number
        period?: {
          /** Format: date */
          startDate?: string
          /** Format: date */
          endDate?: string
        }
      }
    }
    Transaction: {
      /** Format: uuid */
      id?: string
      /** @enum {string} */
      type?: 'income' | 'expense'
      description?: string
      amount?: number
      /** Format: date */
      date?: string
    }
    TransactionListResponse: {
      success?: boolean
      data?: {
        transactions?: components['schemas']['Transaction'][]
        pagination?: components['schemas']['Pagination']
      }
    }
    FundApplication: {
      /** Format: uuid */
      id?: string
      date?: string
      purpose?: string
      /** @enum {string} */
      category?: 'education' | 'health' | 'emergency' | 'equipment'
      /** @enum {string} */
      status?: 'pending' | 'approved' | 'rejected'
      amount?: number
      applicant?: {
        id?: string
        name?: string
      }
    }
    FundApplicationDetail: components['schemas']['FundApplication'] & {
      description?: string
      attachmentUrl?: string
      rejectionReason?: string
      reviewedBy?: {
        id?: string
        name?: string
      }
      /** Format: date-time */
      reviewedAt?: string
      /** Format: date-time */
      createdAt?: string
    }
    FundApplicationListResponse: {
      success?: boolean
      data?: {
        applications?: components['schemas']['FundApplication'][]
        pagination?: components['schemas']['Pagination']
      }
    }
    CashBill: {
      /** Format: uuid */
      id?: string
      billId?: string
      month?: string
      year?: number
      /** @enum {string} */
      status?: 'belum_dibayar' | 'menunggu_konfirmasi' | 'sudah_dibayar'
      /** Format: date */
      dueDate?: string
      totalAmount?: number
    }
    CashBillDetail: components['schemas']['CashBill'] & {
      name?: string
      kasKelas?: number
      biayaAdmin?: number
      /** @enum {string} */
      paymentMethod?: 'bank' | 'ewallet' | 'cash'
      paymentProofUrl?: string
      /** Format: date-time */
      paidAt?: string
      /** Format: date-time */
      confirmedAt?: string
    }
    CashBillListResponse: {
      success?: boolean
      data?: {
        bills?: components['schemas']['CashBill'][]
        pagination?: components['schemas']['Pagination']
      }
    }
    ExportRequest: {
      /** @enum {string} */
      format?: 'xlsx' | 'pdf'
      /** Format: date */
      startDate?: string
      /** Format: date */
      endDate?: string
    }
  }
  responses: {
    /** @description Authentication required or invalid */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorResponse']
      }
    }
  }
  parameters: {
    page: number
    limit: number
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
